### ISSUE TITLE
pass in ipfs.dag instead of creating an IPFS instances

### ISSUE THREAD

**Issue by wanderer** [primea/js-ipfs-wasm-loader#1]
```
const ipfsLoader = new IpfsLoader(ipfs.dag)
```

**Comment by wanderer** [comment]
https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag

**Comment by Silur** [comment]
fixed in https://github.com/primea/js-ipfs-wasm-loader/commit/6778ce015dd6996ea37f8918798e55a4fc3952b8
